// AUTO-GENERATED FILE. DO NOT MODIFY DIRECTLY.
// Run 'npm run sync-permissions' to update from backend.

export const AppActions = {
  Read: 'read',
  Add: 'add',
  Update: 'update',
  Delete: 'delete',
  Toggle: 'toggle',
  Disable: 'disable',
  Assign: 'assign',
  Reorder: 'reorder',
  Export: 'export',
  Import: 'import',
  Cancel: 'cancel',
  View: 'view',
  Sync: 'sync',
  Print: 'print',
  Approve: 'approve',
  Health: 'health',
  Migrations: 'migrations',
  ClearCache: 'clearCache',
  Manage: 'manage',
  Confirm: 'confirm',
  AssignResource: 'assignResource',
  ChangeResource: 'changeResource',
  ChangeStatus: 'changeStatus',
  AssignToNewOperation: 'assignToNewOperation',
  AssignToExistingOperation: 'assignToExistingOperation',
  Release: 'release',
  ViewRelease: 'viewRelease',
  ChangeItemWeight: 'changeItemWeight',
  SaveReceived: 'saveReceived',
  LockWorkOrderReceiving: 'lockWorkOrderReceiving',
  ApproveReceived: 'approveReceived',
  RetryReceived: 'retryReceived',
  RetryProcess: 'retryProcess',
  SaveManualWoProcess: 'saveManualWoProcess',
  Stop: 'stop',
  Resume: 'resume',
  Complete: 'complete',
  Pause: 'pause',
  AddManual: 'addManual',
  ProcessIntoOperation: 'processIntoOperation',
  AssignParallelResource: 'assignParallelResource',
  ViewProcess: 'viewProcess',
  ViewDetails: 'viewDetails',
  RemoveRelatedWorkOrder: 'removeRelatedWorkOrder',
  ConvertToPlanned: 'convertToPlanned',
  ConvertToProduction: 'convertToProduction',
  ChangeName: 'changeName',
  ChangePassword: 'changePassword',
  ResetPassword: 'resetPassword',
  ViewCosting: 'viewCosting',
};
